// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcaumuwhovuelzrxqmbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjYXVtdXdob3Z1ZWx6cnhxbWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODAyNDgsImV4cCI6MjA2MzY1NjI0OH0.P5s39VaadA-EFtANOagAlPCCp6FvADjOZCJaDqNQBrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);